- name: Install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: Installing Package
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: Starting service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
