- name: install nginx server
  hosts: web
  become: yes
  tasks:
  - name: installing package
    ansible.builtin.dnf:
      name: nginx
      state: latest

  - name: starting service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

       