- name: variables
  hosts: localhost
  vars: #varaiabe at play level
    course: Devops with AWS
    trainer: Sivakumar M
    duration: 3.5 months
  tasks:
  vars: #Variable at task level
    course: Terraform
    trainer: Sivakumar M
    duration: 15 hrs
  - name: print information from task level
    ansible.builtin.debug:
      msg: "Hi I am learning Course {{ course }} from Trainer {{ trainer }} and Duration is {{ duration }}"

  - name: print information from play level
    ansible.builtin.debug:
      msg: "Hi I am learning Course {{ course }} from Trainer {{ trainer }} and Duration is {{ duration }}"
    
