- name: variables from files
  hosts: localhost
  vars_files:
    - vars-files
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg:"Hi am learning course {{ Course }} from trainer {{ Trainer }} and duration {{ Duration }}"