- name: install and run nginx
  hosts: web
  become: yes
  tasks:
  - name: install package
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: start and enable service
    ansible.builtin.service:
      name: nginx
      state: installed
      enbled: yes