- name: variables from inventory
  hosts: localhost
  tasks:
  - name: print information
    vars:
      timings: "7:15AM IST"
    ansible.builtin.debug:
      msg: " Hi I am learning Course {{course}} from trainer {{trainer}} duration is:{{duration}} timings are {{timings}}"